#!/usr/bin/env ucode

let as_string = require("core.common").as_string;

// Single source of truth for the tachyon command surface.
//
// It was a local function inside /usr/bin/tachyon, which made it impossible to
// expose a second entry point without copying the table and hoping the copy
// stayed in sync. Both entry points require this module instead.

// Every command defaults to the write role. A command becomes readable only by
// being listed in READ_COMMANDS, so a command nobody reviewed is denied to a
// read-only session rather than opened to it.

const COMMANDS = {
        start: [ "service/lifecycle.uc", "start", 0 ],
        stop: [ "service/lifecycle.uc", "stop", 0 ],
        reload: [ "service/lifecycle.uc", "reload", 1 ],
        reload_firewall: [ "service/lifecycle.uc", "reload-firewall", 0 ],
        dns_failover_apply: [ "service/lifecycle.uc", "dns-failover-apply", 1 ],
        restart: [ "service/lifecycle.uc", "restart", 0 ],
        enable: [ "service/lifecycle.uc", "enable", 0 ],
        disable: [ "service/lifecycle.uc", "disable", 0 ],
        uninstall: [ "service/uninstall.uc", "uninstall", 1 ],
        reset_settings: [ "service/reset.uc", "reset-settings", 1 ],
        delete_section: [ "config/connections.uc", "delete-section", 1 ],
        dnsmasq_restore: [ "service/lifecycle.uc", "dnsmasq-restore", 0 ],
        restore_dnsmasq: [ "service/lifecycle.uc", "dnsmasq-restore", 0 ],
        main: [ "service/lifecycle.uc", "main", 0 ],
        list_update: [ "components/updates.uc", "list-update", 0 ],
        list_update_async: [ "components/updates.uc", "list-update-async", 0 ],
        list_update_status: [ "components/updates.uc", "list-update-status", 0 ],
        list_update_if_due: [ "components/updates.uc", "list-update-if-due", 0 ],
        subscription_update: [ "components/updates.uc", "subscription-update", 2 ],
        subscription_update_async: [ "components/updates.uc", "subscription-update-async", 2 ],
        subscription_update_status: [ "components/updates.uc", "subscription-update-status", 1 ],
        subscription_update_if_due: [ "components/updates.uc", "subscription-update-if-due", 0 ],
        check_proxy: [ "diagnostics/runtime.uc", "check-proxy", 0 ],
        check_nft: [ "diagnostics/runtime.uc", "check-nft", 0 ],
        check_nft_rules: [ "diagnostics/runtime.uc", "check-nft-rules", 0 ],
        check_sing_box: [ "diagnostics/runtime.uc", "check-sing-box", 0 ],
        check_steer: [ "diagnostics/runtime.uc", "check-steer", 0 ],
        check_inbounds_config: [ "diagnostics/runtime.uc", "check-inbounds-config", 0 ],
        check_inbounds: [ "diagnostics/runtime.uc", "check-inbounds", 0 ],
        check_logs: [ "diagnostics/runtime.uc", "check-logs", 0 ],
        check_sing_box_logs: [ "diagnostics/runtime.uc", "check-sing-box-logs", 0 ],
        check_fakeip: [ "diagnostics/runtime.uc", "check-fakeip", 0 ],
        check_zapret_runtime: [ "diagnostics/runtime.uc", "check-zapret-runtime", 0 ],
        check_zapret2_runtime: [ "diagnostics/runtime.uc", "check-zapret2-runtime", 0 ],
        check_byedpi_runtime: [ "diagnostics/runtime.uc", "check-byedpi-runtime", 0 ],
        check_tor_runtime: [ "diagnostics/runtime.uc", "check-tor-runtime", 0 ],
        install_tor: [ "diagnostics/runtime.uc", "install-tor", 0 ],
        neutralize_zapret_defaults: [ "diagnostics/runtime.uc", "neutralize-zapret-defaults", 0 ],
        clash_api: [ "diagnostics/runtime.uc", "clash-api", 4 ],
        show_config: [ "diagnostics/runtime.uc", "show-config", 1 ],
        show_version: [ "diagnostics/runtime.uc", "show-version", 0 ],
        show_sing_box_config: [ "diagnostics/runtime.uc", "show-sing-box-config", 1 ],
        show_sing_box_version: [ "diagnostics/runtime.uc", "show-sing-box-version", 0 ],
        get_status: [ "diagnostics/runtime.uc", "get-status", 0 ],
        get_outbound_metadata: [ "diagnostics/runtime.uc", "get-outbound-metadata", 1 ],
        get_subscription_metadata: [ "diagnostics/runtime.uc", "get-subscription-metadata", 1 ],
        get_sing_box_status: [ "diagnostics/runtime.uc", "get-sing-box-status", 0 ],
        get_engine_status: [ "diagnostics/runtime.uc", "get-engine-status", 0 ],
        get_zapret_status: [ "diagnostics/runtime.uc", "get-zapret-status", 0 ],
        get_zapret2_status: [ "diagnostics/runtime.uc", "get-zapret2-status", 0 ],
        get_byedpi_status: [ "diagnostics/runtime.uc", "get-byedpi-status", 0 ],
        get_wdtt_status: [ "diagnostics/runtime.uc", "get-wdtt-status", 0 ],
        get_olcrtc_status: [ "diagnostics/runtime.uc", "get-olcrtc-status", 0 ],
        get_fptn_status: [ "diagnostics/runtime.uc", "get-fptn-status", 0 ],
        get_tailscale_status: [ "diagnostics/runtime.uc", "get-tailscale-status", 0 ],
        get_tailscale_peers: [ "diagnostics/runtime.uc", "get-tailscale-peers", 0 ],
        tailscale_restart: [ "providers/tailscale/runtime.uc", "start-runtime", 0 ],
        parental_quota_tick: [ "service/parental_quota.uc", "tick", 0 ],
        parental_quota_reset: [ "service/parental_quota.uc", "reset", 0 ],
        failover_check: [ "service/failover.uc", "check", 0 ],
        get_system_info: [ "diagnostics/runtime.uc", "get-system-info", 0 ],
        get_server_capabilities: [ "diagnostics/runtime.uc", "get-server-capabilities", 0 ],
        get_ui_capabilities: [ "service/ui.uc", "get-ui-capabilities", 0 ],
        get_ui_state: [ "service/ui.uc", "get-ui-state", 0 ],
        service_action_async: [ "service/ui.uc", "service-action-async", 1 ],
        service_action_status: [ "service/ui.uc", "service-action-status", 1 ],
        latency_test_async: [ "service/ui.uc", "latency-test-async", 4 ],
        latency_test_status: [ "service/ui.uc", "latency-test-status", 1 ],
        ui_action_ack: [ "service/ui.uc", "action-ack", 2 ],
        generate_reality_keypair: [ "server/service.uc", "generate-reality-keypair", 0 ],
        get_tls_certificate_sha256: [ "server/service.uc", "tls-certificate-sha256", 1 ],
        component_action: [ "components/action.uc", "component-action", 2 ],
        component_action_async: [ "components/updates.uc", "component-action-async", 2 ],
        component_action_status: [ "components/updates.uc", "component-action-status", 1 ],
        component_action_log: [ "components/updates.uc", "component-action-log", 2 ],
        component_list_releases: [ "components/action.uc", "list-component-releases", 2 ],
        component_install_version: [ "components/action.uc", "install-component-version", 2 ],
        component_updates_if_due: [ "components/updates.uc", "component-updates-if-due", 0 ],
        component_auto_update_apply: [ "components/updates.uc", "component-auto-update-apply", 0 ],
        component_update_check_cache: [ "components/updates.uc", "component-update-check-cache", 0 ],
        hosts_list_update: [ "components/hosts.uc", "list-update", 1 ],
        hosts_list_status: [ "components/hosts.uc", "list-status", 0 ],
        extract_ruleset: [ "diagnostics/runtime.uc", "extract-ruleset", 1 ],
        check_dns_available: [ "diagnostics/runtime.uc", "check-dns-available", 0 ],
        global_check: [ "diagnostics/runtime.uc", "global-check", 2 ],
        service_health_check: [ "diagnostics/runtime.uc", "service-health-check", 2 ],
        doctor: [ "diagnostics/runtime.uc", "doctor", 1 ],
        ai_doctor: [ "diagnostics/runtime.uc", "ai-doctor", 1 ],
        ai_doctor_last: [ "diagnostics/runtime.uc", "ai-doctor-last", 0 ],
        apply_quick_fix: [ "diagnostics/runtime.uc", "apply-quick-fix", 1 ],
        lan_clients: [ "diagnostics/runtime.uc", "lan-clients", 0 ],
        toggle_client_bypass: [ "diagnostics/runtime.uc", "toggle-client-bypass", 1 ],
        diagnose_json: [ "diagnostics/runtime.uc", "diagnose-json", 0 ],
        agent_cgi: [ "service/agent_api.uc", "__cgi", 0 ],
        mcp: [ "service/agent_mcp.uc", "", 0 ],
        watchdog: [ "service/watchdog.uc", "", 1 ],
        watchdog_start: [ "service/watchdog.uc", "start-runtime", 0 ],
        watchdog_stop: [ "service/watchdog.uc", "stop-runtime", 0 ],
        ai_heal: [ "service/watchdog.uc", "ai-heal", 0 ],
        ai_status: [ "service/watchdog.uc", "ai-status", 0 ],
        ai_status_full: [ "service/watchdog.uc", "ai-status-full", 0 ],
        telegram: [ "service/telegram.uc", "", 2 ],
        telegram_status: [ "service/telegram.uc", "status", 0 ],
        telegram_start: [ "service/telegram.uc", "start-runtime", 0 ],
        telegram_stop: [ "service/telegram.uc", "stop-runtime", 0 ],
        telegram_diagnose: [ "service/telegram.uc", "diagnose", 0 ],
        validate_nfqws_strategy_json: [ "diagnostics/runtime.uc", "validate-nfqws-strategy-json", 1 ],
        validate_nfqws2_strategy_json: [ "diagnostics/runtime.uc", "validate-nfqws2-strategy-json", 1 ],
        validate_byedpi_strategy_json: [ "diagnostics/runtime.uc", "validate-byedpi-strategy-json", 1 ],
        leak_check: [ "diagnostics/leak_check.uc", "leak-check", 2 ],
        leak_check_async: [ "diagnostics/leak_check.uc", "leak-check-async", 0 ],
        leak_check_status: [ "diagnostics/leak_check.uc", "leak-check-status", 1 ],
        check_ip_leak: [ "diagnostics/leak_check.uc", "ip-leak", 0 ],
        check_dns_leak: [ "diagnostics/leak_check.uc", "dns-leak", 0 ],
        fuzzer_start: [ "diagnostics/fuzzer.uc", "start", 7 ],
        fuzzer_status: [ "diagnostics/fuzzer.uc", "status", 0 ],
        fuzzer_stop: [ "diagnostics/fuzzer.uc", "stop", 0 ],
        fuzzer_apply: [ "diagnostics/fuzzer.uc", "apply", 3 ],
        fuzzer_strategies: [ "diagnostics/fuzzer.uc", "strategies", 1 ],
        fuzzer_generate: [ "diagnostics/fuzzer.uc", "generate", 2 ],
        fuzzer_ai_synthesize: [ "diagnostics/fuzzer.uc", "ai_synthesize", 4 ],
        fuzzer_get_patterns: [ "diagnostics/fuzzer.uc", "get_patterns", 0 ],
        fuzzer_save_patterns: [ "diagnostics/fuzzer.uc", "save_patterns", 1 ],
        fuzzer_reset_patterns: [ "diagnostics/fuzzer.uc", "reset_patterns", 0 ],
        fuzzer_detect_dpi: [ "diagnostics/fuzzer.uc", "detect_dpi", 2 ],
        fuzzer_auto_apply: [ "diagnostics/fuzzer.uc", "auto_apply", 1 ],
        fuzzer_history: [ "diagnostics/fuzzer.uc", "history", 1 ],
        fuzzer_clear_history: [ "diagnostics/fuzzer.uc", "clear_history", 0 ],
        fuzzer_presets_info: [ "diagnostics/fuzzer.uc", "presets_info", 0 ],
        fuzzer_update_presets: [ "diagnostics/fuzzer.uc", "update_presets", 0 ],
        generate_warp: [ "service/warp_generator.uc", "", 2 ],
        package_prerm: [ "service/package.uc", "prerm", 1 ],
        package_postinst: [ "service/package.uc", "postinst", 0 ],
        luci_postinst: [ "service/package.uc", "luci-postinst", 0 ],
        engine_info: [ "service/engine_runtime.uc", "engine-info", 0 ],
        engine_features: [ "service/engine_runtime.uc", "engine-features", 0 ],
        engine_plan: [ "service/engine_runtime.uc", "engine-plan", 1 ],
        engine_switch: [ "service/engine_runtime.uc", "engine-switch", 3 ],
        engine_switch_back: [ "service/engine_runtime.uc", "engine-switch-back", 0 ],
        engine_start: [ "service/engine_runtime.uc", "engine-start", 0 ],
        engine_stop: [ "service/engine_runtime.uc", "engine-stop", 0 ],
        engine_reload: [ "service/engine_runtime.uc", "engine-reload", 1 ],
        engine_status: [ "service/engine_runtime.uc", "engine-status", 0 ],
        engine_apply: [ "service/engine_runtime.uc", "engine-apply", 1 ],
        engine_generate: [ "service/engine_runtime.uc", "engine-generate", 1 ],
        engine_diag: [ "service/engine_runtime.uc", "engine-diag", 0 ],
        engine_explain: [ "service/engine_runtime.uc", "engine-explain", 1 ],
        snapshot_list: [ "service/snapshot.uc", "snapshot-list", 0 ],
        snapshot_save: [ "service/snapshot.uc", "snapshot-save", 1 ],
        snapshot_restore: [ "service/snapshot.uc", "snapshot-restore", 1 ],
        snapshot_delete: [ "service/snapshot.uc", "snapshot-delete", 1 ],
        dns_benchmark: [ "dns/benchmark.uc", "benchmark", 1 ],
        dns_autotune: [ "dns/benchmark.uc", "autotune", 1 ],
        dns_benchmark_async: [ "dns/benchmark.uc", "benchmark_async", 0 ],
        dns_benchmark_status: [ "dns/benchmark.uc", "benchmark_status", 0 ],
        dns_benchmark_stop: [ "dns/benchmark.uc", "benchmark_stop", 0 ],
        dns_benchmark_apply: [ "dns/benchmark.uc", "benchmark_apply", 0 ],
        import_settings: [ "config/migration.uc", "import-settings", 1 ],
        "import-settings": [ "config/migration.uc", "import-settings", 1 ],
        resolve_domain: [ "diagnostics/runtime.uc", "resolve-domain", 1 ],
        "resolve-domain": [ "diagnostics/runtime.uc", "resolve-domain", 1 ],
        reconcile: [ "service/reconciler.uc", "apply", 0 ],
        reconcile_plan: [ "service/reconciler.uc", "plan", 0 ],
        reconcile_status: [ "service/reconciler.uc", "status", 0 ],
        escalation_status: [ "service/watchdog.uc", "escalation-status", 0 ],
        emergency_status: [ "service/watchdog.uc", "emergency-status", 0 ],
        emergency_reset: [ "service/watchdog.uc", "emergency-reset", 0 ],
        emergency_trigger: [ "service/watchdog.uc", "emergency-trigger", 1 ],
        route_explain: [ "diagnostics/route_explain.uc", "explain", 4 ],
        "route-explain": [ "diagnostics/route_explain.uc", "explain", 4 ],
        config_plan: [ "service/config_plan.uc", "plan", 2 ],
        "config-plan": [ "service/config_plan.uc", "plan", 2 ],
        config_validate: [ "service/config_plan.uc", "validate", 1 ],
        "config-validate": [ "service/config_plan.uc", "validate", 1 ],
        known_good: [ "service/known_good.uc", "status", 2 ],
        "known-good": [ "service/known_good.uc", "status", 2 ],
        known_good_status: [ "service/known_good.uc", "status", 2 ],
        "known-good-status": [ "service/known_good.uc", "status", 2 ],
        known_good_promote: [ "service/known_good.uc", "promote", 1 ],
        "known-good-promote": [ "service/known_good.uc", "promote", 1 ],
        known_good_restore: [ "service/known_good.uc", "restore", 1 ],
        "known-good-restore": [ "service/known_good.uc", "restore", 1 ],
        known_good_rollback: [ "service/known_good.uc", "rollback", 1 ],
        "known-good-rollback": [ "service/known_good.uc", "rollback", 1 ],
        known_good_check: [ "service/known_good.uc", "check", 0 ],
        "known-good-check": [ "service/known_good.uc", "check", 0 ],
        support_bundle: [ "service/support_bundle.uc", "create", 3 ],
        "support-bundle": [ "service/support_bundle.uc", "create", 3 ],
        job_list: [ "core/jobs.uc", "list", 0 ],
        "job-list": [ "core/jobs.uc", "list", 0 ],
        job_query: [ "core/jobs.uc", "query", 1 ],
        "job-query": [ "core/jobs.uc", "query", 1 ],
        job_cancel: [ "core/jobs.uc", "cancel", 1 ],
        "job-cancel": [ "core/jobs.uc", "cancel", 1 ],
        job_request_cancel: [ "core/jobs.uc", "request-cancel", 1 ],
        "job-request-cancel": [ "core/jobs.uc", "request-cancel", 1 ],
        job_gc: [ "core/jobs.uc", "gc", 0 ],
        "job-gc": [ "core/jobs.uc", "gc", 0 ],
        event_query: [ "core/events.uc", "query", 0 ],
        "event-query": [ "core/events.uc", "query", 0 ],
        event_tail: [ "core/events.uc", "tail", 0 ],
        "event-tail": [ "core/events.uc", "tail", 0 ],
        event_stats: [ "core/events.uc", "stats", 0 ],
        "event-stats": [ "core/events.uc", "stats", 0 ],
        event_clear: [ "core/events.uc", "clear", 0 ],
        "event-clear": [ "core/events.uc", "clear", 0 ],
        event_record: [ "core/events.uc", "record", 1 ],
        "event-record": [ "core/events.uc", "record", 1 ],
        server_stats: [ "diagnostics/server_stats.uc", "summary", 0 ],
        "server-stats": [ "diagnostics/server_stats.uc", "summary", 0 ],
        server_probe: [ "diagnostics/server_stats.uc", "probe", 2 ],
        "server-probe": [ "diagnostics/server_stats.uc", "probe", 2 ],
        server_probe_all: [ "diagnostics/server_stats.uc", "probe_all", 2 ],
        "server-probe-all": [ "diagnostics/server_stats.uc", "probe_all", 2 ],
        server_best: [ "diagnostics/server_stats.uc", "best", 2 ],
        "server-best": [ "diagnostics/server_stats.uc", "best", 2 ],
        server_query: [ "diagnostics/server_stats.uc", "query", 1 ],
        "server-query": [ "diagnostics/server_stats.uc", "query", 1 ],
        server_stats_reset: [ "diagnostics/server_stats.uc", "reset", 0 ],
        "server-stats-reset": [ "diagnostics/server_stats.uc", "reset", 0 ],
        stability_report: [ "diagnostics/stability.uc", "report", 0 ],
        "stability-report": [ "diagnostics/stability.uc", "report", 0 ],
        stability_status: [ "diagnostics/stability.uc", "status", 0 ],
        "stability-status": [ "diagnostics/stability.uc", "status", 0 ]
    };

// Read-only commands. Anything absent here needs the write role, so adding a
// command to the table above cannot accidentally hand it to a read-only
// session -- the default denies.
const READ_COMMANDS = {
    // introspection
    "show_version": true,
    "show_config": true,
    "show_sing_box_config": true,
    "show_sing_box_version": true,
    "get_status": true,
    "get_outbound_metadata": true,
    "get_subscription_metadata": true,
    "get_sing_box_status": true,
    "get_engine_status": true,
    "get_zapret_status": true,
    "get_zapret2_status": true,
    "get_byedpi_status": true,
    "get_wdtt_status": true,
    "get_olcrtc_status": true,
    "get_fptn_status": true,
    "get_tailscale_status": true,
    "get_tailscale_peers": true,
    "get_system_info": true,
    "get_server_capabilities": true,
    "get_ui_capabilities": true,
    "get_ui_state": true,
    "lan_clients": true,
    "get_tls_certificate_sha256": true,

    // checks that only observe
    "check_proxy": true,
    "check_nft": true,
    "check_nft_rules": true,
    "check_sing_box": true,
    "check_steer": true,
    "check_inbounds": true,
    "check_inbounds_config": true,
    "check_logs": true,
    "check_sing_box_logs": true,
    "check_fakeip": true,
    "check_zapret_runtime": true,
    "check_zapret2_runtime": true,
    "check_byedpi_runtime": true,
    "check_tor_runtime": true,
    "check_dns_available": true,
    "check_ip_leak": true,
    "check_dns_leak": true,
    "leak_check": true,
    "leak_check_status": true,
    "global_check": true,
    "service_health_check": true,
    "doctor": true,
    "ai_doctor": true,
    "ai_doctor_last": true,
    "ai_status": true,
    "ai_status_full": true,
    "diagnose_json": true,
    "failover_check": true,
    "watchdog": true,
    "telegram_status": true,
    "telegram_diagnose": true,
    "engine_info": true,
    "engine_features": true,
    "engine_plan": true,
    "engine_diag": true,
    "engine_explain": true,
    "engine_status": true,
    "route_explain": true,
    "route-explain": true,
    "config_plan": true,
    "config-plan": true,
    "config_validate": true,
    "config-validate": true,
    "resolve_domain": true,
    "resolve-domain": true,
    "validate_nfqws_strategy_json": true,
    "validate_nfqws2_strategy_json": true,
    "validate_byedpi_strategy_json": true,
    "extract_ruleset": true,
    "clash_api": true,

    // job, event and observation surfaces
    "job_list": true,
    "job-list": true,
    "job_query": true,
    "job-query": true,
    "event_query": true,
    "event-query": true,
    "event_tail": true,
    "event-tail": true,
    "event_stats": true,
    "event-stats": true,
    "support_bundle": true,
    "support-bundle": true,
    "snapshot_list": true,
    "server_stats": true,
    "server-stats": true,
    "server_probe": true,
    "server-probe": true,
    "server_probe_all": true,
    "server-probe-all": true,
    "server_best": true,
    "server-best": true,
    "server_query": true,
    "server-query": true,
    "stability_report": true,
    "stability-report": true,
    "stability_status": true,
    "stability-status": true,
    "escalation_status": true,
    "emergency_status": true,
    "known_good": true,
    "known-good": true,
    "known_good_status": true,
    "known-good-status": true,
    "known_good_check": true,
    "known-good-check": true,
    "reconcile_status": true,
    "hosts_list_status": true,
    "dns_benchmark": true,
    "dns_benchmark_status": true,
    "fuzzer_status": true,
    "fuzzer_strategies": true,
    "fuzzer_get_patterns": true,
    "fuzzer_history": true,
    "fuzzer_presets_info": true,

    // status of jobs the write role started
    "list_update_status": true,
    "subscription_update_status": true,
    "service_action_status": true,
    "latency_test_status": true,
    "component_action_status": true,
    "component_action_log": true
};

function command_spec(command) {
    return COMMANDS[as_string(command)];
}

function is_read_command(command) {
    return READ_COMMANDS[as_string(command)] === true;
}

// Spec for a command the read role is allowed to run, or null. The read entry
// point must refuse on null rather than fall back to the full table.
function read_command_spec(command) {
    let name = as_string(command);
    if (!is_read_command(name))
        return null;
    return COMMANDS[name];
}

return {
    command_spec,
    is_read_command,
    read_command_spec
};
