import { describe, expect, it } from 'vitest';
import {
  RPC_METADATA_MAP,
  serializeRpcCliArgs,
  TACHYON_RPC_METHODS,
  validateRpcParams,
} from '../generated/rpcContract';

/**
 * The contract used to be written by hand and described a richer surface than
 * the router actually had: named required parameters, enums, typed objects. It
 * also described a different layer -- 32 of its methods were never called by the
 * frontend, and 60 of the 78 it did call were missing from it.
 *
 * It is now generated by tools/generate_rpc_surface.js from the command table in
 * tachyon/files/usr/bin/tachyon, so what it asserts is what the router does.
 * Two consequences are load-bearing and worth stating rather than papering over:
 *
 *   - the CLI takes positional arguments, so the generator can only name them
 *     arg1..argN. The hand-written names (job_id, action, client) were guesses
 *     that nothing enforced.
 *   - every generated parameter is an optional string, so the type, enum and
 *     object branches of validateRpcParams have no real method to exercise. They
 *     are still worth keeping -- the contract is not the only thing that will
 *     ever feed it -- but they cannot be tested against generated input, and
 *     pretending otherwise is how the old test ended up asserting fiction.
 */
describe('Tachyon RPC Contract', () => {
  describe('Completeness & Schema Integrity', () => {
    it('defines metadata for all registered methods', () => {
      expect(TACHYON_RPC_METHODS.length).toBeGreaterThanOrEqual(200);

      for (const method of TACHYON_RPC_METHODS) {
        const meta = RPC_METADATA_MAP[method];
        expect(meta).toBeDefined();
        expect(meta.name).toBe(method);
        expect(meta.cli_command).toBe(method);
        expect(['read', 'write', 'admin', 'diagnostic']).toContain(meta.acl);
        expect(Array.isArray(meta.params)).toBe(true);
        expect(typeof meta.timeout_ms).toBe('number');
        expect(meta.timeout_ms).toBeGreaterThan(0);
      }
    });

    it('registers each command exactly once', () => {
      const names = TACHYON_RPC_METHODS;
      expect(new Set(names).size).toBe(names.length);
    });

    it('covers the categories the router actually dispatches', () => {
      const categories = new Set(
        Object.values(RPC_METADATA_MAP).map((m) => m.category),
      );

      // These are the prefixes the dispatcher really uses. The old test also
      // wanted 'engine', 'jobs' and 'events', which no module path produces.
      for (const expected of [
        'system',
        'diagnostics',
        'updates',
        'known_good',
        'stability',
        'telegram',
        'fuzzer',
        'ai',
      ]) {
        expect(categories).toContain(expected);
      }
    });

    it('agrees with the read-only entry point about roles', () => {
      // A command the read role can exec must be marked read, and a command
      // that rewrites the router must not be. tachyon_acl_role_split.sh pins the
      // same split from the backend side.
      const readOnly = TACHYON_RPC_METHODS.filter(
        (m) => RPC_METADATA_MAP[m].acl === 'read',
      );
      expect(readOnly.length).toBeGreaterThan(0);
      expect(readOnly.length).toBeLessThan(TACHYON_RPC_METHODS.length);

      for (const destructive of [
        'emergency_reset',
        'apply_quick_fix',
        'component_install_version',
        'snapshot_restore',
        'reconcile',
      ] as const) {
        expect(RPC_METADATA_MAP[destructive]?.acl).toBe('write');
      }
    });
  });

  describe('Runtime Validator (validateRpcParams)', () => {
    it('rejects a method the contract does not know', () => {
      const res = validateRpcParams('definitely_not_a_command' as never, {});
      expect(res.valid).toBe(false);
      expect(res.errors[0]).toContain('Unknown RPC method');
    });

    it('accepts a generated method with no parameters', () => {
      const res = validateRpcParams('get_status', {});
      expect(res.valid).toBe(true);
      expect(res.errors).toHaveLength(0);
    });

    it('accepts positional arguments as strings', () => {
      const res = validateRpcParams('service_action_async', {
        arg1: 'restart',
      });
      expect(res.valid).toBe(true);
    });

    it('rejects a non-string positional argument', () => {
      const res = validateRpcParams('service_action_async', {
        arg1: 42 as unknown as string,
      });
      expect(res.valid).toBe(false);
      expect(res.errors.some((e) => e.includes('must be a string'))).toBe(true);
    });
  });

  describe('CLI Arguments Serializer (serializeRpcCliArgs)', () => {
    it('emits only the command name when it takes no arguments', () => {
      // The CLI invocation is `tachyon <command> [args...]`, so the command is
      // the first element and the caller appends nothing after it.
      const args = serializeRpcCliArgs('get_status', {});
      expect(args).toEqual(['get_status']);
    });

    it('serialises positional arguments after the command name', () => {
      const args = serializeRpcCliArgs('service_action_async', {
        arg1: 'restart',
      });
      expect(args).toEqual(['service_action_async', 'restart']);
    });
  });
});
